apiVersion: v1
data:
  readonly.macaroon: <get base64 encoded admin.macaroon file here from your lnd node>
  tls.cert: <get base64 encoded tls.cert file here from your lnd node>
  creds.json: <get base64 encoded google creds.json file here>
kind: Secret
metadata:
  creationTimestamp: "2020-09-06T14:30:57Z"
  name: lnd-scb-backup
  namespace: stef
  resourceVersion: "107997575"
  selfLink: /api/v1/namespaces/stef/secrets/lnd-scb-backup
  uid: 6169c7f2-6ab4-4f90-bbab-e8c49fcddef5
type: Opaque
